version: 2
updates:
  # 維護 npm (Angular/Frontend) 的依賴項
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    # 設定 Reviewer (可選，填入您的 GitHub ID)
    # reviewers:
    #   - "yuanfu8899"
